
#All features that require being on the client
["Client Features"]
	#The range in which shinies will sparkle. Set to -1 to disable. Default: 25.0
	#Range: -1.0 ~ 500.0
	shinySparkleRange = 25.0
	#The length of each line of lore in the item tooltip. Set to 0 to disable. Default: 60
	autoWrapLoreLength = 60
	#The volume of the shiny sparkle sound. Set to 0 to disable. Default and maximum: 1.0
	#Range: 0.0 ~ 1.0
	shinySparkleVolume = 1.0

#All features that require being on the server
["Server Features"]
	#If pokemon should be prevented from trampling crops. Default: true
	antiTrampleCrops = true
	#The rate in which Zygarde Cores should spawn when it's stormy. Rate is 1/<rate>. Set to 0 to disable. Default: 7
	#Range: 0 ~ 9999
	zygardeStormCoreRate = 7
	#If Pokemon chat replacement should be enabled. Allows players to use [Pokemon] and [Party] to show their pokemon in chat. Default: true
	enablePokemonChat = true
	#How often a Zygarde cell should attempt to spawn (in seconds). Does not guarantee a spawn. Set to 0 to disable. Default: 30
	#Range: 0 ~ 9999
	zygardeSpawnTime = 30
	#If fox pokemon should become immune to vanilla berry bushes & heal when right clicked with berries. Default: true
	foxesLoveBerries = true
	#The chance of a spawn attempt being 'lucky'. Lucky attempts will spawn with a higher chance of being near the player. Chance is 1/<rate> Set to 0 to disable. Default: 4.
	#Range: 0 ~ 9999
	zygardeLuckyAttemptRate = 4
	#The level a pokemon can begin to be hypertrained. Default: 50 (PixelTweaks), 100 (Pixelmon)
	#Range: 1 ~ 100
	hypertrainLevel = 50
	#If apricorns should randomly drop when they are ripe. Default: true
	randomlyDropRipeApricorns = false
	#If Backpack integration should be enabled (supports 4 backpack mods). Default: true
	backpacksIntegration = true
	#If Pixelmon Healers should drop themselves when broken. Default: true
	healersDropThemselves = true

