
[waila]
	#If true, will only show information when crouching.
	wailaUseCrouchKey = false

	[waila.blocks]
		#If true, will show the block information in Waila.
		wailaShowBlockInformation = true
		#If true, will show the block tooltip in Waila.
		wailaBlocksShowTooltip = true
		#If true, will show the block information in Waila.
		wailaBlocksShowInformation = true

	[waila.entities]
		#If true, will show the entity information in Waila.
		wailaShowEntityInformation = true
		#If true, will show the description of the pokémon.
		wailaEntityShowPokemonDescription = false
		#If true, will show the owner's name of the pokémon.
		wailaEntityShowPokemonOwner = true
		#If true, will show the level of the pokémon.
		wailaEntityShowPokemonLevel = true
		#If true, will show the Pokédex Number of the pokémon.
		wailaEntityShowPokemonPokedexNumber = false
		#If true, will show the Generation of the pokémon.
		wailaEntityShowPokemonGeneration = false
		#If true, will show the EV (effort value) yield of the pokémon.
		wailaEntityShowPokemonEVYield = true
		#If true, will show the type information of the pokémon.
		wailaEntityShowPokemonTypeInformation = true
		#If true, will show the nature information of the pokémon.
		wailaEntityShowPokemonNatureInformation = false
		#If true, will show the growth information of the pokémon.
		wailaEntityShowPokemonGrowthInformation = false
		#If true, will show the EV (effort value) stats of the pokémon.
		wailaEntityShowPokemonEVs = true
		#If true, will show the IV (individual values) stats of the pokémon.
		wailaEntityShowPokemonIVs = false
		#If true, will show the type match-up information of the pokémon.
		wailaEntityShowPokemonTypeMatchupInformation = false
		#If true, will show if the pokémon has been caught.
		wailaEntityShowPokemonCaught = true

[theoneprobe]
	#If true, will only show information when crouching.
	topUseCrouchKey = true

	[theoneprobe.blocks]
		#If true, will show the block information in The One Probe.
		topShowBlockInformation = true
		#If true, will show the block tooltip in The One Probe.
		topBlocksShowTooltip = true
		#If true, will show the block information in The One Probe.
		topBlocksShowInformation = true

	[theoneprobe.entities]
		#If true, will show the entity information in The One Probe.
		topShowEntityInformation = true
		#If true, will show the description of the pokémon.
		topEntityShowPokemonDescription = false
		#If true, will show the owner's name of the pokémon.
		topEntityShowPokemonOwner = true
		#If true, will show the level of the pokémon.
		topEntityShowPokemonLevel = true
		#If true, will show the Pokédex Number of the pokémon.
		topEntityShowPokemonPokedexNumber = false
		#If true, will show the Generation of the pokémon.
		topEntityShowPokemonGeneration = false
		#If true, will show the EV (effort value) yield of the pokémon.
		topEntityShowPokemonEVYield = false
		#If true, will show the type information of the pokémon.
		topEntityShowPokemonTypeInformation = true
		#If true, will show the nature information of the pokémon.
		topEntityShowPokemonNatureInformation = false
		#If true, will show the growth information of the pokémon.
		topEntityShowPokemonGrowthInformation = true
		#If true, will show the EV (effort value) stats of the pokémon.
		topEntityShowPokemonEVs = true
		#If true, will show the IV (individual values) stats of the pokémon.
		topEntityShowPokemonIVs = false
		#If true, will show the type match-up information of the pokémon.
		topEntityShowPokemonTypeMatchupInformation = false
		#If true, will show if the pokémon has been caught.
		topEntityShowPokemonCaught = true

